name: Docker Image CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file golang/1.16/alpine/Dockerfile --tag test:$(date +%s) # dynamic --file field?